applications:
  - name: Teams
    display: 2
    side: right
    executable: "teams.exe"
  - name: Outlook
    display: 2
    side: left
    executable: "outlook.exe"
  - name: Slack
    display: 3
    side: right
    executable: "slack.exe"
  - name: Notion
    display: 2
    side: left
    executable: "notion.exe"
